// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtxkgingsusqacsquzqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0eGtnaW5nc3VzcWFjc3F1enFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Njk3MzQsImV4cCI6MjA3MjU0NTczNH0.cOETB9CXgM1xJdydJHWLGqKUe_VeGL5q4_804FUlV_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});